### ISSUE TITLE
Cannot read property 'count' of undefined ejs

### ISSUE THREAD

**Issue by tryon-dev** [chaun14/chaunServer-full#9]
Bonjour, j'ai installé ce dashboard mais une erreur est arrivé quand je l'ai lancé

TypeError: /home/debian/mc/views/dashboard.ejs:95
    93|                                     </div>
    94|                                     <div class="number dashtext-1">
 >> 95|                                         <%= stats[0].count %>
    96|                                     </div>
    97|                                 </div>
    98| 

Cannot read property 'count' of undefined
    at eval (eval at compile (/home/debian/mc/node_modules/ejs/lib/ejs.js:662:12), <anonymous>:13:35)
    at dashboard (/home/debian/mc/node_modules/ejs/lib/ejs.js:692:17)
    at tryHandleCache (/home/debian/mc/node_modules/ejs/lib/ejs.js:272:36)
    at View.exports.renderFile [as engine] (/home/debian/mc/node_modules/ejs/lib/ejs.js:489:10)
    at View.render (/home/debian/mc/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/debian/mc/node_modules/express/lib/application.js:640:10)
    at Function.render (/home/debian/mc/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/home/debian/mc/node_modules/express/lib/response.js:1012:7)
    at /home/debian/mc/routes/dashboard.js:49:9
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by chaun14** [comment]
C'est un petit bug qui se règle facilement, charge juste une fois la page /files et le dashboard fonctionnera

**Comment by tryon-dev** [comment]
merci mais je n'ai pas trop compris le fonctionnement du serveur (a quoi cela sert et quel fichier mettre si on n'a un helios launcher) ???
